version: "3"
services:
  web-server:
    image: node:16-alpine
    volumes:
      - type: bind
        source: ../
        target: /code
    working_dir: /code
    command: sh -c "yarn start:dev"
    ports:
      - "3000:3000"
  db:
    image: mongo:latest
    restart: always